services:
  db:
    image: postgres:18
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql

  django:
    build: .
    env_file: ".env"
    container_name: django-docker
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
     - DATABASE_ENGINE=${POSTGRES_ENGINE}
     - DATABASE_HOST=${POSTGRES_HOST}
     - DATABASE_PORT=${POSTGRES_PORT}
    ports:
      - "8000:8000"

volumes:
  data:


